language: go

go:
  - 1.8.1

install:
  # TODO (kinkade): Fix this. If upstream accepts my PR, then this can be
  # drastically simpler. If they don't accept it, then move this to an m-lab
  # repo.
  - SCRIPT_EXPORTER_URI=github.com/nkinkade/script_exporter;
    SCRIPT_EXPORTER_BRANCH=mlab;
    go get -d $SCRIPT_EXPORTER_URI;
    git -C $GOPATH/src/$SCRIPT_EXPORTER_URI;
    git checkout origin/$SCRIPT_EXPORTER_BRANCH;
    go install $SCRIPT_EXPORTER_URI

script:
  - "cp $GOPATH/bin/script_exporter $TRAVIS_BUILD_DIR/"
  - "$TRAVIS_BUILD_DIR/travis/install_gcloud.sh"

deploy:
  # Sandbox - conditionally deploy to GCP project mlab-sandbox
  - provider: script
    script: "$TRAVIS_BUILD_DIR/deploy_script_exporter.sh mlab-sandbox SERVICE_ACCOUNT_mlab_sandbox"
    skip_cleanup: true
    on:
      repo: m-lab/prometheus-script-exporter
      branch: sandbox-*
      condition: "$TRAVIS_EVENT_TYPE == push"

  # Staging - conditionally deploy to GCP project mlab-staging
  - provider: script
    script: "$TRAVIS_BUILD_DIR/deploy_script_exporter.sh mlab-staging SERVICE_ACCOUNT_mlab_staging"
    skip_cleanup: true
    on:
      repo: m-lab/prometheus-script-exporter
      branch: master
      condition: "$TRAVIS_EVENT_TYPE == push"

  # Production - conditionally deploy to GCP project mlab-oti
  - provider: script
    script: "$TRAVIS_BUILD_DIR/deploy_script_exporter.sh mlab-oti SERVICE_ACCOUNT_mlab_oti"
    skip_cleanup: true
    on:
      repo: m-lab/prometheus-script-exporter
      tags: true
